/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const component$: typeof import('@builder.io/qwik')['component$']
  const ref: typeof import('vue')['ref']
  const useSignal: typeof import('@builder.io/qwik')['useSignal']
  const watchEffect: typeof import('vue')['watchEffect']
}
